spring.application.name=Songify

## POSTGRESQL
spring.datasource.url=jdbc:postgresql://localhost:54320/postgres
spring.datasource.username=user
spring.datasource.password=admin

## HIKARI
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=5

## HIBERNATE
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

## Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration/general,classpath:db/migration/inserts
spring.flyway.schemas=public

### JWT
#auth.jwt.issuer=Songify
#auth.jwt.expirationMinutes=10
#auth.jwt.secret=${JWT_SECRET}

## FOR FRONTEND COOKIES
server.ssl.key-store-type=PKCS12
server.ssl.key-store=classpath:certificate.p12
server.ssl.key-store-password=12345

server.ssl.enabled=true
server.port=8443

## OAUTH 2
spring.security.oauth2.client.registration.google.client-id=928531035736-kkuop001s20v77mo9ctbkk7lc6fe2618.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=${OAUTH2_SECRET}
spring.security.oauth2.client.registration.google.redirect-uri=https://localhost:8443/login/oauth2/code/google
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://accounts.google.com
