ALTER TABLE album
    ADD version BIGINT DEFAULT 0 NOT NULL;

ALTER TABLE artist
    ADD version BIGINT DEFAULT 0 NOT NULL;

ALTER TABLE genre
    ADD version BIGINT DEFAULT 0 NOT NULL;

ALTER TABLE song
    ADD version BIGINT DEFAULT 0 NOT NULL;