CREATE SEQUENCE IF NOT EXISTS song_seq START WITH 1 INCREMENT BY 50;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE TABLE song
(
    id           BIGSERIAL PRIMARY KEY ,
    title         VARCHAR(255) NOT NULL,
    release_date TIMESTAMP WITHOUT TIME ZONE,
    duration     BIGINT,
    language     VARCHAR(255)
);
